#import "../fragments/club.gql"

query getStandings {
  standings {
    position {
      current
      previous
    }
    club {
      ...club
    }
    played
    won
    drawn
    lost
    goals {
      for
      against
      difference
    }
    points
    form {
      id
      kickoff
      home
      against {
        ...club
      }
      result
    }
    nextMatch {
      kickoff
      against {
        ...club
      }
    }
  }
}

